### ISSUE TITLE
Word Model has to be created in Database

### ISSUE THREAD

**Issue by KDharmindar** [KDharmindar/Wordutopia#3]
Word model has to be created in .models.py file.

**Comment by KDharmindar** [comment]
Fields for Words are as follows
1.	ID = int 
2.	UserID = int
3.	Word = String
4.	Pronunciation = String
5.	Phrase = String
6.	Hint = String
7.	Definition = String
8.	Synonym = String
9.	IsShareOnline = bit
10.	IsFavourite = bit
11.	IsSkip = bit
12.	Appearance = int
13.	WAppreance = int
14.	Score = int
15.	AdditionInfo = String

**Comment by vinodvaghella** [comment]
Fields for words are now created.
